
package view;

import classes.Aluno;
import dao.AlunoDao;
import bean.AlunoBean;


public class FormAlunos extends javax.swing.JFrame {

    /**
     * Creates new form FormAlunos
     */
    public FormAlunos() {
        initComponents();
    }  
    
    private Aluno montaAluno() {
        Aluno aluno = new Aluno();
        aluno.setNome(txtNome.getText());
        aluno.setRgm(txtRgm.getText());
        aluno.setNota1(Float.parseFloat(txtNota1.getText()));
        aluno.setNota2(Float.parseFloat(txtNota2.getText()));
        
        return aluno;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNota2 = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtRgm = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("RGM:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nota 1:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 130, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nota 2:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 70, 20);
        getContentPane().add(txtNota2);
        txtNota2.setBounds(110, 170, 100, 20);
        getContentPane().add(txtNome);
        txtNome.setBounds(110, 90, 320, 20);
        getContentPane().add(txtRgm);
        txtRgm.setBounds(110, 50, 100, 20);
        getContentPane().add(txtNota1);
        txtNota1.setBounds(110, 130, 100, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensagem"));

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 240, 400, 110);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandos"));

        btnCalcular.setText("Calcular");
        btnCalcular.setEnabled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 40, 160, 310);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TODOS OS EVENTOS ESTÃO DISPONÍVEIS A PARTIR DO BOTÃO PESQUISAR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 10, 620, 17);

        setSize(new java.awt.Dimension(689, 405));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (txtRgm.getText().equals("")){
            lblMensagem.setText("Preencha o RGM do aluno");
        }else if(txtNome.getText().equals("")){
            lblMensagem.setText("Preencha o Nome do aluno");
        }else if(txtNota1.getText().equals("")){
            lblMensagem.setText("Preencha a Nota1");
        }else if(txtNota2.getText().equals("")){
            lblMensagem.setText("Preencha a Nota2");
        }else{
            Aluno aluno = montaAluno();
            //String resp = new AlunoDAO().gravaAluno(aluno);
            String resp = new AlunoDao().gravaAluno(aluno);
            
            if(resp.equals("OK")){
                lblMensagem.setText("Aluno incluído com sucesso");
                txtRgm.setText("");
                txtNome.setText("");
                txtNota1.setText("");
                txtNota2.setText("");
            }else{
                lblMensagem.setText("" + resp);
            }
        }
        
        btnCalcular.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtRgm.setEnabled(true);
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        if (txtRgm.getText().equals("")) {
            lblMensagem.setText("Preencha o RGM do aluno");
        } else {
            Aluno aluno = new AlunoDao().getAluno(txtRgm.getText());
            if (aluno == null) {
                txtNome.setText("");
                txtNota1.setText("");
                txtNota2.setText("");
                lblMensagem.setText("Aluno não encontrado!");
               
            } else {
                txtRgm.setEnabled(false);
                txtNome.setText(aluno.getNome());
                txtNota1.setText("" + aluno.getNota1());
                txtNota2.setText("" + aluno.getNota2());
                lblMensagem.setText("Aluno encontrado!");
                btnCalcular.setEnabled(true);
                btnAlterar.setEnabled(true);
                btnExcluir.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        if (txtRgm.getText().equals("")) {
                lblMensagem.setText("Preencha o RGM do aluno");
            } else if (txtNome.getText().equals("")) {
                lblMensagem.setText("Preencha o nome do aluno");
            } else if (txtNota1.getText().equals("")) {
                lblMensagem.setText("Preencha corretamente a Nota1");
            } else if (txtNota2.getText().equals("")) {
                lblMensagem.setText("Preencha corretamente a Nota2");
            } else {
                String media = new AlunoBean().calculaMedia(Float.parseFloat(txtNota1.getText()),
                Float.parseFloat(txtNota2.getText()));
                lblMensagem.setText(media);
                
                btnCalcular.setEnabled(false);
        }
        
        
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtRgm.setEnabled(true);
        
        txtRgm.setText("");
        txtNome.setText("");
        txtNota1.setText("");
        txtNota2.setText("");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtRgm.setText("");
        txtNome.setText("");
        txtNota1.setText("");
        txtNota2.setText("");
        lblMensagem.setText("");
        
        btnCalcular.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtRgm.setEnabled(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        String resp = new AlunoDao().deleteAluno(txtRgm.getText());
        
        if(resp.equals("OK")){
            txtRgm.setText("");
            txtNome.setText("");
            txtNota1.setText("");
            txtNota2.setText("");
            lblMensagem.setText("Aluno exluido com sucesso");
        }else{
            lblMensagem.setText("" + resp);
        }
            
        btnCalcular.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtRgm.setEnabled(true);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
               
        if (txtRgm.getText().equals("")){
            lblMensagem.setText("Preencha o RGM do aluno");
        }else if(txtNome.getText().equals("")){
            lblMensagem.setText("Preencha o Nome do aluno");
        }else if(txtNota1.getText().equals("")){
            lblMensagem.setText("Preencha a Nota1");
        }else if(txtNota2.getText().equals("")){
            lblMensagem.setText("Preencha a Nota2");
        }else{
            Aluno aluno = montaAluno();
            //String resp = new AlunoDAO().gravaAluno(aluno);
            String resp = new AlunoDao().alteraAluno(aluno);
            
            if(resp.equals("OK")){
                lblMensagem.setText("Aluno alterado com sucesso");
            }else{
                lblMensagem.setText("" + resp);
            }
        }
        //lblMensagem.setText("" + resp);
        
        btnCalcular.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtRgm.setEnabled(true);
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtRgm;
    // End of variables declaration//GEN-END:variables
}
